# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(254, 131, 127)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_1.setGeometry(QtCore.QRect(270, 70, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_1.setFont(font)
        self.lbl_1.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:1.138, fx:0.493864, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(86, 43, 43);")
        self.lbl_1.setObjectName("lbl_1")
        self.lineEdit_login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login.setGeometry(QtCore.QRect(300, 200, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border: 2px solid rgb(223, 148, 111);\n"
"border-color: rgb(208, 135, 104);")
        self.lineEdit_login.setMaxLength(15)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(300, 250, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setAutoFillBackground(False)
        self.lineEdit_password.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"border: 2px solid rgb(223, 148, 111);\n"
"border-color: rgb(208, 135, 104);")
        self.lineEdit_password.setMaxLength(15)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_2.setGeometry(QtCore.QRect(190, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(19)
        self.lbl_2.setFont(font)
        self.lbl_2.setObjectName("lbl_2")
        self.lbl_3 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_3.setGeometry(QtCore.QRect(190, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(19)
        self.lbl_3.setFont(font)
        self.lbl_3.setObjectName("lbl_3")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(310, 302, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(19)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(67, 45, 33)")
        self.btn_login.setObjectName("btn_login")
        self.lbl_answer = QtWidgets.QLabel(self.centralwidget)
        self.lbl_answer.setGeometry(QtCore.QRect(180, 460, 501, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.lbl_answer.setFont(font)
        self.lbl_answer.setText("")
        self.lbl_answer.setObjectName("lbl_answer")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(290, 370, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(19)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(67, 45, 33)")
        self.btn_register.setObjectName("btn_register")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.lbl_1.setText(_translate("MainWindow", "Вход в систему"))
        self.lbl_2.setText(_translate("MainWindow", "Логин:"))
        self.lbl_3.setText(_translate("MainWindow", "Пароль:"))
        self.btn_login.setText(_translate("MainWindow", "Войти"))
        self.btn_register.setText(_translate("MainWindow", "Регистрация"))
